"""Initial migration

Revision ID: 510edd5ba344
Revises: f54813eca650
Create Date: 2025-09-16 11:02:39.586982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510edd5ba344'
down_revision = 'f54813eca650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
